# NUMPY

In [16]:
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
a.shape

(3, 5)

In [17]:
a.ndim

2

In [19]:
a.dtype.name

'int32'

In [20]:
a.itemsize

4

In [21]:
a.size

15

In [22]:
type(a)

numpy.ndarray

In [24]:
b = ([6, 7, 8])
type(b)

list

In [25]:
c = (6, 7, 8)
type(c)

tuple

In [26]:
b

[6, 7, 8]

# Array Creation

In [28]:
a = np.array([2, 3, 4])
a



array([2, 3, 4])

In [29]:
a.dtype

dtype('int32')

In [31]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [34]:
b = np.array([(1, 2), (3, 4)])
b

array([[1, 2],
       [3, 4]])

In [35]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [36]:
c = np.array([[1, 2], [3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [38]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [43]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [47]:
a = np.ones((2, 3, 4))
a

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [48]:
a = np.empty((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

## Crear secuencias de números

In [49]:
a = np.arange(10,30,5)
a

array([10, 15, 20, 25])

In [50]:
a = np.arange(10,40,5)
a

array([10, 15, 20, 25, 30, 35])

In [51]:
a = np.arange(10,30,2)
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

### Repaso

In [2]:
import numpy as np
a = np.array ([2, 3, 4])
a


dtype('int32')

In [3]:
a.dtype

dtype('int32')

In [6]:
b = np.array([1.2, 3.5, 5.1])
b

array([1.2, 3.5, 5.1])

In [7]:
b.dtype

dtype('float64')

In [8]:
b = np.array([(1.5, 2, 3), (4, 5, 6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [9]:
c = np.array([[1, 2],[3, 4]], dtype=complex)
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [10]:
d = np.zeros((3, 4))
d

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
e = np.ones((2, 3, 4))
e

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [22]:
f = np.ones((1, 3))
f

array([[1., 1., 1.]])

In [27]:
g = np.ones((2, 3, 3, 4))
g

array([[[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]],


       [[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]]])

## 1 - 1D array creation functions

In [31]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
b = np.arange(2, 10, dtype=float)
b

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [33]:
c = np.arange(2, 3, 0.1)
c

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [34]:
d = np.linspace(1., 4., 6)
d

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

## 2 - 2D array creation functions

In [35]:
a = np.eye(3)  # Matriz identidad
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
b = np.eye(3, 5)
b

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [37]:
a = np.diag([1, 2, 3])  # Matriz diagonal
a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [40]:
b = np.diag([1, 2, 3], 1)
b

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [41]:
c = np.array([[1, 2], [3, 4]])
c

array([[1, 2],
       [3, 4]])

In [42]:
np.diag(c)

array([1, 4])

### Replicating, joining, or mutating existing arrays

In [45]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
b += 1
print('a =', a, '; b =', b)

a = [2 3 3 4 5 6] ; b = [2 3]


In [46]:
a # en este ejemplo creamos a "b" como una vista de "a"

array([2, 3, 3, 4, 5, 6])

# numpy.copy

In [47]:
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1
print('a =', a, '; b =', b)

a = [1 2 3 4] ; b = [2 3]
